#!/bin/bash
#We use this launcher to avoid random segmentation faults
#Because of the multithreading and SIMD, some segmentation faults can occur
#If it happens, we just restart the program, until the job is done

exec 2> /dev/null
errors = 0
while [ 1 ]; do
  errors=$((errors+1))
  ./find $@ && break
  if (( $errors == 10 )); then
    exec 2>&1
    echo "Error, too many segmentation faults"
    break
  fi
done
